### ISSUE TITLE
Problem with launching the application (CoreWebView2)

### ISSUE THREAD

**Issue by MaciejPokrzywinski** [DynamicsNinja/AdvancedAppManager#1]
A problem was encountered while launching the application. The problem occurred on Windows 11 Enterprise 21H2 OS Build 22000.527
The sequence of actions performed:
1. XrmToolBox v1.2022.2.54 is started.
2. Logged into Power Platform environment
3. Started the Addvanced App Manager
4. Received an error while Loading Images

Content of the error:

Unhandled exception has occulted in your application. If you click Continue. the application will ignore this error and attempt to continue. If you click Quit. the application will close immediately. 

The instance of CoreWebView2 is uninitialized and unable to complete this operation. See EnsureCoreWebView2Async. 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: The instance of CoreWebView2 is uninitialized and unable to complete this operation. See EnsureCoreWebView2Async.
   at Microsoft.Web.WebView2.WinForms.WebView2.VerifyInitializedGuard()
   at Microsoft.Web.WebView2.WinForms.WebView2.NavigateToString(String htmlContent)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at System.Windows.Forms.ComboBox.set_SelectedItem(Object value)
   at Fic.XTB.AdvancedAppManager.AdvancedAppManager.cbApp_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at Fic.XTB.AdvancedAppManager.AdvancedAppManager.<GetApps>b__40_1(RunWorkerCompletedEventArgs args)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by DynamicsNinja** [comment]
I tried to reproduce the error on my machine and it's working just fine. There was a problem in the past when XTB introduced new DLLs that auto-updater didn't do it right so the only way to fix it was the manual download of the new XTB version.

Can you please check if you get the same error on manually downloaded XTB?

**Comment by MaciejPokrzywinski** [comment]
I downloaded again XrmToolBox, the problem disappeared, thanks for help ;)
